fix:improve PictorialBarSeriesOption
apache/echarts pull request #17155
Opened 2022-06-04 04:50 UTC by dmzc

## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

### Fixed issues

## Details

### Before: What was the problem?

### After: How is it fixed in this PR?

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

## Others

### Merging options

- [ ] Please squash the commits into a single one when merging.

### Other information

2022-06-06 02:53 UTC, Ovilia requested changes
Please update PR description to let us know what this PR does and why it's necessary.

2022-06-06 03:37 UTC, dmzc commented
> Please update PR description to let us know what this PR does and why it's necessar

2022-06-06 03:39 UTC, dmzc commented
> Please update PR description to let us know what this PR does and why it's necessary.

The PR description is completed

2022-06-07 03:28 UTC, Ovilia commented
I check the code and the following series don't have `SeriesEncodeOptionMixin`. @100pah Can you confirm if there are any missing by mistake?

- Treemap
- Tree
- Sunburst
- Lines
- Graph
- Sankey
- ThemeRiver
- Pictorial (the only one that has `encode` in the doc)

2022-06-07 03:28 UTC, Ovilia approved these changes

2022-06-07 07:29 UTC, merged

2022-06-07 07:38 UTC, 100pah commented
@Ovilia 

> I check the code and the following series don't have SeriesEncodeOptionMixin. @100pah Can you confirm if there are any missing by mistake?

> Treemap
> Tree
> Sunburst
> Lines
> Graph
> Sankey
> ThemeRiver
> Pictorial (the only one that has encode in the doc)


This series theoretically can use `encode`, but seams rarely used? We can probably add `encode` 
Tree based data source (`Treemap`, `Tree`, `Sunburst`)  and graph based data source (`Graph`, `Sankey `) theoretically can use `encode`, but we might not ready to use it (e.g.,  no test case yet).

`Lines` and `ThemeRiver ` have special data source, which we are not sure whether it is suitable to use `encode` yet.