feat(legend): add legendmouseover legendmouseout event (#18144)
apache/echarts pull request #18164
Opened 2023-01-11 08:38 UTC by sz-p

## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?

add legend event `legendmouseover` `legendmouseout`

### Fixed issues

#18144 

## Details

### Before: What was the problem?

Stop data carousel when mouse hover on legend must customizing legend elements with HTML

see demo:

https://codepen.io/plainheart/pen/xxJRdam

### After: How does it behave after the fixing?

Stop data carousel with legend event `legendmouseover` `legendmouseout`

see demo:

https://stackblitz.com/edit/js-q9vzb5?file=index.js

## Document Info

One of the following should be checked.

- [ ] This PR doesn't relate to document changes
- [x] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

## Misc

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

## Others

### Merging options

- [ ] Please squash the commits into a single one when merging.

### Other information

2024-10-09 20:02 UTC, oom- commented
Hello, could someone go forward on this ?

2024-10-10 01:48 UTC, sz-p commented
Awaiting for review

2024-11-06 07:55 UTC, Ovilia requested changes
Sorry for the late review. I think this PR is generally good. Please merge from the master to resolve the conflict and I'll have a quick review again. Please also add a test case.

2024-11-06 07:55 UTC, Ovilia commented on src/component/legend/legendAction.ts
> +            isSelected = legendModel.isSelected(payload.name);
This is perhaps no longer needed. You make merge the current master code and have a double check.

2024-11-06 07:55 UTC, Ovilia commented on src/component/legend/legendAction.ts
> +            isSelected = legendModel.isSelected(payload.name);
You should update the `LegendSelectMethodNames` after merging from master.

2025-03-17 11:25 UTC, sz-p commented on src/component/legend/LegendView.ts
>                  itemGroup.on('click', curry(dispatchSelectAction, name, null, api, excludeSeriesId))
Thank you for your comments and great suggestions.

I didn't consider the `triggerEvent` option, and event name need orthogonal composition.

It was my mistake.

I have modified the code, add `legend.triggerEvent`.  please help me review it again.

2025-03-27 10:59 UTC, 100pah approved these changes

2025-03-27 10:59 UTC, merged

2025-04-03 02:10 UTC, sz-p commented on src/component/legend/LegendView.ts
> +                    if (triggerEvent) {
I will do this later

2025-04-09 11:17 UTC, sz-p commented on src/component/legend/LegendView.ts
> +                    if (triggerEvent) {
@plainheart 

It's in https://github.com/apache/echarts/pull/20907 

Please help me to review. 

Thanks.