fix[utils]avoid invalid-type
apache/echarts pull request #18995
Opened 2023-08-15 18:51 UTC by serfend

## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

### Fixed issues

## Details

### Before: What was the problem?

when user use
{
   formatter:x=>1, // a number
}
error will occurred "replace is not a function"

### After: How does it behave after the fixing?

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

## Misc

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

## Others

### Merging options

- [ ] Please squash the commits into a single one when merging.

### Other information

2023-08-29 08:46 UTC, Ovilia requested changes
`formatter:x=>1` doesn't return expected type so it's an error from the user's side. Functions like `trim` expect a string as input so it's not necessary to convert it into a string. So I'm afraid I have to close this PR until you make a solid point on why this should be done inside ECharts.

2023-08-30 06:25 UTC, Ovilia commented
As stated above, formatter should return string type. Wrong input, wrong output. Thanks for your contribution and I'm going to close this PR.

2023-08-30 06:25 UTC, closed without merging

2023-08-30 07:01 UTC, serfend commented
i'm so sorry for issue been closed,but someone event could input anything like ''or'union'select'@@version()--' if he wants , thats can be Vulnerability in the future.

2023-08-30 07:02 UTC, serfend commented
attacker has chance to exploit it by require('child_process') to execute '/bin/bash' in node.js server which contains echart