Create langAR.ts
apache/echarts pull request #19214
Opened 2023-10-16 23:41 UTC by OthmanAliModaes

Adding **Arabic** language.

## Brief Information

This pull request is in the type of:
- Add new language.

### What does this PR do?
- Add **Arabic** language file: **src/i18n/langAR.ts**

### Other information
**- in progress...**

2023-10-17 08:06 UTC, Ovilia requested changes
Thanks for contribution. Why are most of them not translated?

2023-10-17 11:46 UTC, OthmanAliModaes commented
I will translate the rest in a few hours.

2023-10-18 02:27 UTC, plainheart requested changes

2023-10-18 02:27 UTC, plainheart commented on src/i18n/langAR.ts
> +        ],
It looks like the abbreviation is the same as the full form. Besides, the month items seem not to be sorted from 1~12 and the dayOfWeek items seem not to be sorted from Sunday-Saturday.

Ref: https://github.com/amcharts/amcharts5/blob/master/src/locales/ar.ts#L227C14-L266

2023-10-18 20:17 UTC, OthmanAliModaes commented on src/i18n/langAR.ts
> +        ],
The problem is not in the code, but in the code editor, as it displays texts that contain RTL languages ​​in reverse.
I suffer from this problem a lot, as an Arab software developer.
The code display is wrong, but the output is correct.
The same applies to the order of days.

EX:

    var monthAbb = [
        'يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو',
        'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'
    ]

    console.log(monthAbb[0]) // يناير = January
    console.log(monthAbb[11]) // ديسمبر = December

    var dayOfWeek = [
        'الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'
    ]
    console.log(dayOfWeek[0]) // الأحد = Sunday
    console.log(dayOfWeek[6]) // السبت = Saturday

2023-10-18 20:35 UTC, plainheart commented on src/i18n/langAR.ts
> +        ],
Thanks for explanation. Get it.

2023-10-18 20:36 UTC, plainheart approved these changes

2023-10-18 20:38 UTC, merged