feat(axis): break on the axis
apache/echarts pull request #19459
Opened 2024-01-02 11:11 UTC by Ovilia

## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?

![image](https://github.com/user-attachments/assets/7a0a2812-1e4c-4c5d-a1d9-b3f349a6980d)

Provide a way to make break axes that may range too wide.

This is also helpful for expressing the lunch break (11:30-13:00) on intraday stock trading charts.

![image](https://github.com/user-attachments/assets/fb9128f2-6884-479f-8c01-3782accc913a)

This PR also changes `indicesOfNearest` from `DataStore` to `Series` so that when in axisPointer, we can compare the data in the view coordinate rather ran data value, so that the nearest data is more intuitive since it's nearer to the mouse position.

### Fixed issues

## Document Info

One of the following should be checked.

- [ ] This PR doesn't relate to document changes
- [x] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

At present a usage document is added in https://github.com/apache/echarts/pull/19459#issuecomment-2748824472 for v6.0.0-beta.
The full document is coming. 

## Misc

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

When doing visual tests agains `v6` branches, there are 4 diffs:

- `axis-break`: This is the new test file for this feature so it's expected to be different
- `tooltip-axisPointer-snap`: This is the new test file for `indicesOfNearest` and it checks if axisPointer snaps to the nearest data in view coord instead of data value so it's expected to be different
- `area-large`: Due to the change of `indicesOfNearest`, it's now always get the nearest data. But before, some position may don't show tooltip (probably due to large data filtering). So it's expected to be different.
- `pie-label-extreme`: After adding the logic to hiding label elements with zero width and height, the pie labelLines with no label text (due to truncation) will not be displayed. This is a more reasonable presentation because it seems to be not expected to show labelLine when there is not label displayed.

![截屏2025-01-15 17 19 24](https://github.com/user-attachments/assets/ff059057-3040-44b8-b9fd-c5f5b8a37f97)

See the full test report:

[report.html.zip](https://github.com/user-attachments/files/18422239/report.html.zip)

## Others

### Merging options

- [ ] Please squash the commits into a single one when merging.

### Other information

2024-01-02 11:15 UTC, Ovilia commented
Discussion: Should this feature be called "axis breaking" or "axis collapsing"? This may probably depend on if I can implement break folding/unfolding feature.

I think the [HighCharts implementation](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/axisbreak/break-visualized/) is quite tricky for the users. I wisht to implement axis broken style by default so that it won't be misleading to viewers if developers aren't very experienced in dataviz and don't know how to (or why should) let viewers understand this is an axis skipped some ranges.

2024-02-10 05:03 UTC, Chatchawanp501 approved these changes

2025-03-24 16:42 UTC, 100pah requested changes

2025-03-24 17:03 UTC, 100pah commented
# About the additional PR #20857

At the beginning I just reviewed https://github.com/apache/echarts/pull/19459 as usual. After providing several comments, I started writing some code to validate the correction of my suggestions. As the code had been more refined, I began the formal implementation and aimed to merge it to https://github.com/apache/echarts/pull/19459.

Summary of the modification of this new PR:
+ Fix all of the suggestions I commented in the review.
+ Added some new features and changed some echarts API introduced in #19459.
+ Performed some refactors about `scale` and `time axis` in order to clarify the code.
+ Added numerous test cases in `test/axis-break.html` `test/axis-break-2.html` `test/axis-break-3.html` `test/axis-break-4.html`.


## New features and API changes from the original PR

This changes and new features we can discuss whether to accept. **Correct me if I'm wrong in any places.**


### Revert the modification of pie label layout
IMO the result is not correct then before:
When label is out of the canvas, is will be truncated. When partial text is out of the canvas, the text is truncated and the label line is displayed. With the new added code, when all of the text is out of the canvas, the label line disappears and causing it looks like there is no label at all. It does not conform with the concept of "truncation", i.e., show part of something to allow the user know the existence, even if it is not able to be fully displayed.

Moreover, hovering on the label line, even the label is fully out of the canvas, user can still get the label info by tooltip displayed. The new impl removes this feature, which is not correct.


### Remove @ts-ignore and type `any` encountered
@ts-ignore and type `any` should not be used unless no other solution is available (which is rare); otherwise, TS support in echarts could gradually break and introduce vulnerability in future modifications or refactors.

### Fix the constant change of the zigzag shape
The zigzag shape change constantly, even if just clicking on legend, which is unexpected.

### Add animation to zigzag shape
Make it move smoothly, as ticks, labels, splitLine did.

### Add a "break line" effect on axis line
It might be awkward without it, since it is supposed to convey the sense of "axis break".
Add option `axisLine.breakLine` to switch it.


### The naming of break parameters
This new PR modify and unify the parameters regarding axis break in both echarts option, event/action, callbacks:

+ In label formatter, the paramters are changed to:
    ```js
    axisLabel.formatter(value, index, extra) {
        // Previous: extra.breakStart extra.breakEnd
        // Modified to:
        console.log(extra.break);
        // extra: {
        //     break: {
        //         start: number
        //         end: number
        //     }
        // }
        // And whether it's a break label can be determined by:
        if (extra.break) {
            // It's a break label.
        }
    }
    ```
+ In action/event:
    ```js
    // The name of break related action is changed to `updateAxisBreak`
    // and the corresponding event is `axisBreakUpdated`, follow the convention of other similar action/event.
    // And the previous two action 'axisBreakRevert' and 'axisBreakExpand' has been unified to `updateAxisBreak`.
    // And enforce users to provide axis index/id/name to determine which axis is targeted, since there might be more than one axes. This follows the style of the exisiting API (such as, `chart.converToPixel`).
    // The detailed reason: See the comment in `src/component/axis/install.ts`

    chart.dispatchAction({
        'updateAxisBreak',
        yAxisIndex: 0, // or 'all',
        // Or
        //  yAxisId: 'xxx',
        //  yAxisName: 'xxx'
        breaks: [{
            start: xxx,
            end: xxx
        }]
    })

    chart.on('axisBreakUpdated', event => {
        // event: {
        //     breaks: [{
        //         start: number
        //         end: number
        //     }],
        //     ...
        // }
    });
    ```

**PENDING of naming (to be discussed):**
+ Should we rename `break.start/end` to `break.min/max`? The terms `min/max` implies the bigger-smaller relationship, which is not conveyed by `start/end`. And `min/max` has been used in axis related echarts options, such as `axis.min` `axis.max` `axis.showMinLabel`. For historical reason, `start`/`end` is also used in one case: `dataZoom.start`/`end`, but less common than `min`/`max` among echarts options.
+ Should we rename the TS type `ScaleBreak` (or `ScaleBreakXxx`) to `AxisBreak`(or `AxisBreakXxx`)? Currently among the break related type/function/variable names, some are called AxisBreak and others are called ScaleBreak.


### Supported percentage value in `break.gap`
In #19459 the gap can only be a value, with the unit of data (rather than pixel). It causes a constant change in the pixel size of the break are (zigzag shape) when axis extent modified (typically by clicking the legend or moving the dataZoom). And it might brings troubles to users to estimate a proper gap value to make it look appropriate considering the variation of data.

Supporting a pixel gap might be good but complicated.
In the new PR, a percent gap is suppored, where the the percent is based on the axis length, addressed the configurating by visual rather than by data, and keep the visual size of break areas constant.
(Note, the visual size would be changed slightly when there are multiple breaks in one axis and half of a break area is out of the axis extent. But that bad case is not significant and rarely met. The bad case results from the complexity of the math approach.)

Currently the `break.gap` can be:
```js
    // - `number`: The unit is the same as data value, the same as `start`/`end`, not pixel.
    // - `string`:
    //     - Like '35%'. A percent over the axis extent. Useful for keeping the pixel size of break areas
    //       consistent despite variations in `series.data`, which cannot be achieved by `number`.
    //     - Also support numeric string like `'123'`, means `123`, following convention.
    // - If ommitted, means 0.
    gap?: number | string,
```

### Parsing/validation of the input of breaks
In the #19459 there is no parsing/validation, which is error-prone. The new PR adds parsing/validations and separates the data type before and after parsing to clarify the code.

### Fix the data->pixel and pixel->data bug
In #19459, when here is breaks, pixel->data is buggy. Fixed it.

### Regarding formatter of break labels
#19459 introduced `breakFromatter`. But I think we should still use the existing `axisLabel.formatter` rather then introduce a new formatter. See details in https://github.com/apache/echarts/pull/19459/files#diff-1a28ee5654787a889174196b6b3935a68f016e40cf962975a35f31655dfce53fR238

### Added auto break label adjustment to avoid overlap and remove the special handling for gap 0
In #19459, when gap is 0, the break label is displayed like `100 ~ 20000` by default and the formatter callback (if any) is called only for break start but omit break end. This design might brings complextiy to users, and takes too much space if it is a yAxis label, even out of screen by default, not widely applicable the rotation of labels.

In the new PR, this special handling is removed. In all cases, the break start and break end are handled as separate labels, and an automatic overlap escaping logic is performed. See the code in `component/axis/axisBreakHelper.ts#adjustBreakLabelPair`.

**It is worth noting that this feature requires the PR https://github.com/ecomfe/zrender/pull/1115 to be merged into zrender/v6 branch.**


### Regarding time axis

+ Regarding `axisLabel.formatter: {year: 'xxx', month: 'xxx', ...}`, the option of `axisLabel.formatter.inherit` and `axisLabel.formatter.none` has been removed.
    + `axisLabel.formatter.none` is documented in <https://echarts.apache.org/en/optio [...]

2025-03-27 18:47 UTC, Sisi-Qin commented
Hey Olivia,

WoW great to see this feature got picked up!!! I searched this feature on EChart 2/3 years ago, and had no luck. But finally, I am excited to see an implementation will be shipped with EChart V6! Thank you for the amazing work! ⭐ ⭐ ⭐ 

Just a quick question, when can we consume this feature? I see EChart plans to release V6 on April 15th, is this still the plan? If yes, are we able to consume any pre-released version or release candidates prior to release date? We are currently using EChart V5 and will probably need to work on backward incompatibility as major version bumps. 

Again tons of thanks for working on this exciting product! I look forward to hearing back from your team 😆 

Best,
Sisi

2025-03-31 07:13 UTC, Ovilia commented on src/coord/axisHelper.ts
> +    const breakLabelFormatter = labelModel.get('breakFormatter');
I agree that using a single formatter is a better idea. I kind of forgot why I used an additional `breakFormatter` at that time. Probably I didn't know how to pass the break - related parameters if I didn't do it this way.

2025-03-31 08:52 UTC, Ovilia commented on src/scale/Scale.ts
> +     * Whether a value is in broken range (not including either ends)
I believe why `break.end` and `break.start` are treated differently is due to some mapping problems, which I'm not sure can be ignored after I gave up implementing with category axis.

2025-04-01 06:35 UTC, Ovilia commented on src/label/labelLayoutHelper.ts
> +        }
I have to agree with not removing labelLines in these cases after second thinking.

2025-04-02 22:09 UTC, Sisi-Qin commented
> @Sisi-Qin Thank you for your affirmation of the Apache ECharts product. As you can see in this PR, we have several major PRs in the review process. There are quite a number of modification suggestions involved, and the release time is also affected by whether the review comments back and forth meet our expectations. Currently, we hope to complete the code development work by April 15th and finish the release by the end of April. However, this schedule may be influenced by various factors. We sincerely appreciate your understanding.

Thank you for letting me know Ovilia. That sounds great, I look forward to the new release!

2025-04-10 07:12 UTC, 100pah approved these changes

2025-04-10 07:14 UTC, merged