feat(log): allows zero and negativ values
apache/echarts pull request #20266
Opened 2024-08-18 15:38 UTC by callepaeth

There are problems when using axis of type 'log' with zero and negative values.

This change allow zero and negative values, when useing type 'log' for an axis.

src/coord/axisAlignTicks.ts and src/scale/Log.ts will use log() as mathLog from src/util/math.ts.

2024-08-19 02:22 UTC, Ovilia requested changes
Logarithms of zero and negative numbers are not defined in the real numbers. So I don't think it's proper to support this.

2024-08-19 05:01 UTC, callepaeth commented
> Logarithms of zero and negative numbers are not defined in the real numbers. So I don't think it's proper to support this.

I understand this. It was the minimal change to support it.
What about going deeper, and change only the functions where the special handling is needed ?

scale/Log.ts:{setExtent,unionExtent,contain,normalize}
coord/axisAlignTicks.ts:alignScaleTicks

If yes, how should it be done ? create a function ?  programm it out ?
if using a function, how should it be named ?

regards.

2024-08-19 05:18 UTC, callepaeth commented
After thinking about it ...

What about naming the function in util/math.ts 'symlog' or 'synmetricLog' and use it only where it's  needed in:
   scale/Log.ts:{setExtent,unionExtent,contain,normalize}
   coord/axisAlignTicks.ts:alignScaleTicks

regards.

2024-08-19 06:18 UTC, Ovilia commented
Could you be more specific about in what scenerio do you need this feature?

2024-08-19 09:33 UTC, callepaeth commented
I will prepare an example.

2024-08-20 06:09 UTC, callepaeth commented
[balance.txt](https://github.com/user-attachments/files/16669687/balance.txt)

Here the example. The chart is more compact with 'log'.
I found some other problems, so the MR is not so good, I will change it.

regars

2024-08-20 14:54 UTC, closed without merging